### ISSUE TITLE
sorting HTML column as number 

### ISSUE THREAD

**Issue by steveyang2002** [fooplugins/FooTable#659]
I am using latest version 3.1.4. I have table like this:
<table id="cert_table" class="table" data-paging="true"  data-sorting="true" data-cascade="true" data-filtering="true" data-show-toggle="false" >
            <thead>
                <tr>
                    <th data-type="html" data-sort-value="number">Quote ID</th>
                    <th data-breakpoints="xs">Certificate Number</th>
                    <th >Office</th>
                   ......
                </tr>                            
            </thead>
            <tbody>
               <tr>
                   <td class="footable-first-visible" style="display: table-cell;"><a target="_blank" href="index.php?edit=1&id=9">9</a></td>
                   <td style="display: table-cell;"></td>
                   <td style="display: table-cell;">Other Broker</td>
                 ......
               </tr>
               <tr>
                   <td class="footable-first-visible" style="display: table-cell;"><a target="_blank" href="index.php?edit=1&id=1">1</a></td>
                   <td style="display: table-cell;"></td>
                   <td style="display: table-cell;">Broker B</td>
                 ......
               </tr>
               <tr>
                   <td class="footable-first-visible" style="display: table-cell;"><a target="_blank" href="index.php?edit=1&id=10">10</a></td>
                   <td style="display: table-cell;"></td>
                   <td style="display: table-cell;"> Broker A</td>
                 ......
               </tr>
            </tbody>
</table>

When sorting with Quote ID column, it sorts as text not number . I got:
1
10
9
How do I fix this? 
Thank you,

**Comment by poulnike** [comment]
@steveyang2002 
it fix in new version. Now only develop branch
`Fixed an issue in the sorting component where values in a number column supplied as strings were being sorted as such and not as numbers as they should.`

#595

**Comment by poulnike** [comment]
@steveyang2002 
Hurried.
http://fooplugins.github.io/FooTable/docs/components/sorting.html
Column options -> Sorted
`To supply this option through data attributes you must specify the attribute on the cell element.`

**Comment by steveyang2002** [comment]
@poulnike ,

Thank you for your comments. I added code in  #595 to .js. 
```
(function($, F){

	/**
	 * This is supplied either the cell value or jQuery object to parse. A value must be returned from this method and will be used during sorting operations.
	 * @param {(*|jQuery)} valueOrElement - The value or jQuery cell object.
	 * @returns {*}
	 */
	F.NumberColumn.prototype.sortValue = function(valueOrElement){
		// if we have an element or a jQuery object use jQuery to get the data value or pass it off to the parser
		if (F.is.element(valueOrElement) || F.is.jq(valueOrElement)){
			var data = $(valueOrElement).data('sortValue');
			return F.is.number(data) ? data : this.parser(valueOrElement);
		}
		// if options are supplied with the value
		if (F.is.hash(valueOrElement) && F.is.hash(valueOrElement.options)){
			if (F.is.string(valueOrElement.options.sortValue)) return this.parser(valueOrElement);
			if (F.is.number(valueOrElement.options.sortValue)) return valueOrElement.options.sortValue;
			if (F.is.number(valueOrElement.value)) return valueOrElement.value;
		}
		if (F.is.string(valueOrElement)) return this.parser(valueOrElement);
		if (F.is.number(valueOrElement)) return valueOrElement;
		return null;
	};

})(jQuery, FooTable);
```

But it still not working. Can't figure out what went wrong. My table code:

```
<table id="cert_table" class="table" data-paging="true"  data-sorting="true" data-cascade="true" data-filtering="true" data-show-toggle="false" >
            <thead>
                <tr>
                    <th data-type="html" data-sort-value="number">Quote ID</th>
                    <th data-breakpoints="xs">Certificate Number</th>
                    <th >Office</th>
                   ......
                </tr>                            
            </thead>
            <tbody>
               <tr>
                   <td class="footable-first-visible" style="display: table-cell;"><a target="_blank" href="index.php?edit=1&id=9">9</a></td>
                   <td style="display: table-cell;"></td>
                   <td style="display: table-cell;">Other Broker</td>
                 ......
               </tr>
               <tr>
                   <td class="footable-first-visible" style="display: table-cell;"><a target="_blank" href="index.php?edit=1&id=1">1</a></td>
                   <td style="display: table-cell;"></td>
                   <td style="display: table-cell;">Broker B</td>
                 ......
               </tr>
               <tr>
                   <td class="footable-first-visible" style="display: table-cell;"><a target="_blank" href="index.php?edit=1&id=10">10</a></td>
                   <td style="display: table-cell;"></td>
                   <td style="display: table-cell;"> Broker A</td>
                 ......
               </tr>
            </tbody>
</table>
```

**Comment by poulnike** [comment]
@steveyang2002 
https://jsfiddle.net/poulnike/1jhgm0vg/1/

**Comment by steveyang2002** [comment]
@poulnike ,

Thank you so much. I used it wrong =)

**Comment by steveush** [comment]
This is now resolved with the release of 3.1.5
